export default {
    "pue_status": [
      {
        "id": "383",
        "id_pel_pln": "321100322678",
        "nama_pel_pln": "PT TELKOM SULSEL",
        "tarif_pel_pln": "LB3",
        "daya_pel_pln": "690000",
        "lokasi_pel_pln": "MAKASAR",
        "alamat_pel_pln": "JL.BALAIKOTA",
        "gedung": "WITEL + STO",
        "divre_kode": "TLK-r7000000",
        "divre_name": "DIVISI REGIONAL 7 KAWASAN TIMUR INDONESIA",
        "witel_kode": "DTT-ka200000",
        "witel_name": "TELKOM SULSEL (MAKASAR)",
        "sto_kode": "",
        "sto_name": "PoP Balaikota",
        "tipe": "MIX",
        "rtu_kode": "",
        "is_offline": false,
        "is_online": true
      },
      {
        "id": "384",
        "id_pel_pln": "321209187305",
        "nama_pel_pln": "GD TRASMISI MEKANIK",
        "tarif_pel_pln": "LB3",
        "daya_pel_pln": "345000",
        "lokasi_pel_pln": "MAKASAR",
        "alamat_pel_pln": "JL.A PETTARANI",
        "gedung": "STO",
        "divre_kode": "TLK-r7000000",
        "divre_name": "DIVISI REGIONAL 7 KAWASAN TIMUR INDONESIA",
        "witel_kode": "DTT-ka200000",
        "witel_name": "TELKOM SULSEL (MAKASAR)",
        "sto_kode": "",
        "sto_name": "PoP Pettarani",
        "tipe": "STO",
        "rtu_kode": "",
        "is_offline": false,
        "is_online": true
      },
      {
        "id": "388",
        "id_pel_pln": "321201117969",
        "nama_pel_pln": "KTR WIL 10 TELKOM",
        "tarif_pel_pln": "B3",
        "daya_pel_pln": "865000",
        "lokasi_pel_pln": "Makassar",
        "alamat_pel_pln": "JL. AP PETTARANI,MAKASSAR SELATAN",
        "gedung": "WITEL",
        "divre_kode": "TLK-r7000000",
        "divre_name": "DIVISI REGIONAL 7 KAWASAN TIMUR INDONESIA",
        "witel_kode": "DTT-ka200000",
        "witel_name": "TELKOM SULSEL (MAKASAR)",
        "sto_kode": "",
        "sto_name": "Ktr TREG-7",
        "tipe": "OFFICE",
        "rtu_kode": "",
        "is_offline": false,
        "is_online": false
      },
      {
        "id": "390",
        "id_pel_pln": "321400336726",
        "nama_pel_pln": "KTR SENT TEL OTOMAT",
        "tarif_pel_pln": "LB3",
        "daya_pel_pln": "345000",
        "lokasi_pel_pln": "MAKASAR",
        "alamat_pel_pln": "JL.KAKATUA",
        "gedung": "STO",
        "divre_kode": "TLK-r7000000",
        "divre_name": "DIVISI REGIONAL 7 KAWASAN TIMUR INDONESIA",
        "witel_kode": "DTT-ka200000",
        "witel_name": "TELKOM SULSEL (MAKASAR)",
        "sto_kode": "",
        "sto_name": "CNDC Mattoangin",
        "tipe": "MIX",
        "rtu_kode": "",
        "is_offline": false,
        "is_online": true
      },
      {
        "id": "398",
        "id_pel_pln": "321101357408",
        "nama_pel_pln": "KANTOR TELKOM",
        "tarif_pel_pln": "B2",
        "daya_pel_pln": "147000",
        "lokasi_pel_pln": "MAKASAR",
        "alamat_pel_pln": "JL.AP PETARRANI",
        "gedung": "STO",
        "divre_kode": "TLK-r7000000",
        "divre_name": "DIVISI REGIONAL 7 KAWASAN TIMUR INDONESIA",
        "witel_kode": "DTT-ka200000",
        "witel_name": "TELKOM SULSEL (MAKASAR)",
        "sto_kode": "",
        "sto_name": "STO PANAKUKANG",
        "tipe": "MIX",
        "rtu_kode": "",
        "is_offline": false,
        "is_online": false
      },
      {
        "id": "406",
        "id_pel_pln": "325100043251",
        "nama_pel_pln": "PT TELKOM PAREPARE",
        "tarif_pel_pln": "B2",
        "daya_pel_pln": "131000",
        "lokasi_pel_pln": "MATTIROTASI",
        "alamat_pel_pln": "JL. GANGAWA",
        "gedung": "STO",
        "divre_kode": "TLK-r7000000",
        "divre_name": "DIVISI REGIONAL 7 KAWASAN TIMUR INDONESIA",
        "witel_kode": "DTT-kb200000",
        "witel_name": "TELKOM SULSEL BARAT (PARE-PARE)",
        "sto_kode": "",
        "sto_name": "STO Parepare",
        "tipe": "STO",
        "rtu_kode": "",
        "is_offline": false,
        "is_online": false
      },
      {
        "id": "407",
        "id_pel_pln": "326100098108",
        "nama_pel_pln": "SBK PERUMTEL",
        "tarif_pel_pln": "B2",
        "daya_pel_pln": "105000",
        "lokasi_pel_pln": "Pagimana",
        "alamat_pel_pln": "JL.SALAK SAWERIGADING",
        "gedung": "STO",
        "divre_kode": "TLK-r7000000",
        "divre_name": "DIVISI REGIONAL 7 KAWASAN TIMUR INDONESIA",
        "witel_kode": "DTT-kb200000",
        "witel_name": "TELKOM SULSEL BARAT (PARE-PARE)",
        "sto_kode": "",
        "sto_name": "STO Palopo",
        "tipe": "STO",
        "rtu_kode": "",
        "is_offline": false,
        "is_online": false
      },
      {
        "id": "408",
        "id_pel_pln": "329100012820",
        "nama_pel_pln": "KTR TELKOM",
        "tarif_pel_pln": "B2",
        "daya_pel_pln": "66000",
        "lokasi_pel_pln": "Kab. Mamuju",
        "alamat_pel_pln": "JL.BAU MASSEPE, MANAKKARA",
        "gedung": "",
        "divre_kode": "TLK-r7000000",
        "divre_name": "DIVISI REGIONAL 7 KAWASAN TIMUR INDONESIA",
        "witel_kode": "DTT-kb200000",
        "witel_name": "TELKOM SULSEL BARAT (PARE-PARE)",
        "sto_kode": "",
        "sto_name": "STO MAMUJU",
        "tipe": "MIX",
        "rtu_kode": "",
        "is_offline": false,
        "is_online": false
      },
      {
        "id": "394",
        "id_pel_pln": "312100018175",
        "nama_pel_pln": "KTR.DAERAH TELEPON",
        "tarif_pel_pln": "B2",
        "daya_pel_pln": "197000",
        "lokasi_pel_pln": "PALU KOTA",
        "alamat_pel_pln": "JL. K. DAHLAN",
        "gedung": "STO",
        "divre_kode": "TLK-r7000000",
        "divre_name": "DIVISI REGIONAL 7 KAWASAN TIMUR INDONESIA",
        "witel_kode": "DTT-kc200000",
        "witel_name": "TELKOM SULTENG (PALU)",
        "sto_kode": "",
        "sto_name": "STO Palu-1",
        "tipe": "STO",
        "rtu_kode": "",
        "is_offline": false,
        "is_online": false
      },
      {
        "id": "409",
        "id_pel_pln": "319000046462",
        "nama_pel_pln": "S.TELEPON OTOMAT",
        "tarif_pel_pln": "B2",
        "daya_pel_pln": "82500",
        "lokasi_pel_pln": "PALU",
        "alamat_pel_pln": "JL.A. YANI CA005218, KANTOR CABANG LUWUK.",
        "gedung": "STO + PLASA",
        "divre_kode": "TLK-r7000000",
        "divre_name": "DIVISI REGIONAL 7 KAWASAN TIMUR INDONESIA",
        "witel_kode": "DTT-kc200000",
        "witel_name": "TELKOM SULTENG (PALU)",
        "sto_kode": "",
        "sto_name": "STO Luwuk",
        "tipe": "MIX",
        "rtu_kode": "",
        "is_offline": false,
        "is_online": false
      },
      {
        "id": "410",
        "id_pel_pln": "312100260513",
        "nama_pel_pln": "PT. TELKOM",
        "tarif_pel_pln": "B2",
        "daya_pel_pln": "105000",
        "lokasi_pel_pln": "PALU",
        "alamat_pel_pln": "JL. KIJANG",
        "gedung": "STO",
        "divre_kode": "TLK-r7000000",
        "divre_name": "DIVISI REGIONAL 7 KAWASAN TIMUR INDONESIA",
        "witel_kode": "DTT-kc200000",
        "witel_name": "TELKOM SULTENG (PALU)",
        "sto_kode": "",
        "sto_name": "STO Palu-2",
        "tipe": "STO",
        "rtu_kode": "",
        "is_offline": false,
        "is_online": false
      },
      {
        "id": "395",
        "id_pel_pln": "323300016703",
        "nama_pel_pln": "K.SENTRAL TEL OTOMAT",
        "tarif_pel_pln": "B2",
        "daya_pel_pln": "147000",
        "lokasi_pel_pln": "MAKASSAR",
        "alamat_pel_pln": "JL.HALU OLEO",
        "gedung": "STO",
        "divre_kode": "TLK-r7000000",
        "divre_name": "DIVISI REGIONAL 7 KAWASAN TIMUR INDONESIA",
        "witel_kode": "DTT-kd200000",
        "witel_name": "TELKOM SULTRA (KENDARI)",
        "sto_kode": "",
        "sto_name": "STO Kendari-1",
        "tipe": "STO",
        "rtu_kode": "",
        "is_offline": false,
        "is_online": false
      },
      {
        "id": "411",
        "id_pel_pln": "328100062166",
        "nama_pel_pln": "STDI TELKOM BAU2",
        "tarif_pel_pln": "B2",
        "daya_pel_pln": "131000",
        "lokasi_pel_pln": "Sulawesi Tenggara",
        "alamat_pel_pln": "JL.SULTAN HASSANUDIN,BAU BAU KOTA",
        "gedung": "STO + PLASA",
        "divre_kode": "TLK-r7000000",
        "divre_name": "DIVISI REGIONAL 7 KAWASAN TIMUR INDONESIA",
        "witel_kode": "DTT-kd200000",
        "witel_name": "TELKOM SULTRA (KENDARI)",
        "sto_kode": "",
        "sto_name": "STO Baubau",
        "tipe": "MIX",
        "rtu_kode": "",
        "is_offline": false,
        "is_online": false
      },
      {
        "id": "412",
        "id_pel_pln": "323800041848",
        "nama_pel_pln": "SBK TELPON KOLAKA",
        "tarif_pel_pln": "B2",
        "daya_pel_pln": "66000",
        "lokasi_pel_pln": "Sulawesi Tenggara",
        "alamat_pel_pln": "JL.WR SUTPRATMAN .",
        "gedung": "STO + PLASA",
        "divre_kode": "TLK-r7000000",
        "divre_name": "DIVISI REGIONAL 7 KAWASAN TIMUR INDONESIA",
        "witel_kode": "DTT-kd200000",
        "witel_name": "TELKOM SULTRA (KENDARI)",
        "sto_kode": "",
        "sto_name": "STO Kolaka",
        "tipe": "MIX",
        "rtu_kode": "",
        "is_offline": false,
        "is_online": false
      },
      {
        "id": "385",
        "id_pel_pln": "311900357591",
        "nama_pel_pln": "PT. TELKOM INDONESIA",
        "tarif_pel_pln": "B3",
        "daya_pel_pln": "555000",
        "lokasi_pel_pln": "PANIKI",
        "alamat_pel_pln": "JL. WIRATAMA PANIKI BAWAH",
        "gedung": "",
        "divre_kode": "TLK-r7000000",
        "divre_name": "DIVISI REGIONAL 7 KAWASAN TIMUR INDONESIA",
        "witel_kode": "DTT-kf200000",
        "witel_name": "TELKOM SULUT MALUT (MENADO)",
        "sto_kode": "",
        "sto_name": "PoP Paniki",
        "tipe": "MIX",
        "rtu_kode": "",
        "is_offline": false,
        "is_online": false
      },
      {
        "id": "386",
        "id_pel_pln": "311000485647",
        "nama_pel_pln": "KTR TELEPON OTOMAT",
        "tarif_pel_pln": "B3",
        "daya_pel_pln": "555000",
        "lokasi_pel_pln": "MENADO",
        "alamat_pel_pln": "JL.MASJID RAYA MANADO SELATAN",
        "gedung": "WITEL + STO",
        "divre_kode": "TLK-r7000000",
        "divre_name": "DIVISI REGIONAL 7 KAWASAN TIMUR INDONESIA",
        "witel_kode": "DTT-kf200000",
        "witel_name": "TELKOM SULUT MALUT (MENADO)",
        "sto_kode": "",
        "sto_name": "PoP MOC",
        "tipe": "MIX",
        "rtu_kode": "",
        "is_offline": false,
        "is_online": false
      },
      {
        "id": "393",
        "id_pel_pln": "412600246482",
        "nama_pel_pln": "S. T. O",
        "tarif_pel_pln": "B2",
        "daya_pel_pln": "131000",
        "lokasi_pel_pln": "Kab Tator",
        "alamat_pel_pln": "JL.MERPATI.RYN TERNATE",
        "gedung": "STO",
        "divre_kode": "TLK-r7000000",
        "divre_name": "DIVISI REGIONAL 7 KAWASAN TIMUR INDONESIA",
        "witel_kode": "DTT-kf200000",
        "witel_name": "TELKOM SULUT MALUT (MENADO)",
        "sto_kode": "",
        "sto_name": "STO Ternate",
        "tipe": "MIX",
        "rtu_kode": "",
        "is_offline": false,
        "is_online": false
      },
      {
        "id": "392",
        "id_pel_pln": "411020206925",
        "nama_pel_pln": "KANDATEL AMBON",
        "tarif_pel_pln": "B3",
        "daya_pel_pln": "555000",
        "lokasi_pel_pln": "ambon",
        "alamat_pel_pln": "JL.PATTIMURA /10264 RAYON KOTA AMBON",
        "gedung": "STO",
        "divre_kode": "TLK-r7000000",
        "divre_name": "DIVISI REGIONAL 7 KAWASAN TIMUR INDONESIA",
        "witel_kode": "DTT-lb200000",
        "witel_name": "TELKOM MALUKU (AMBON)",
        "sto_kode": "",
        "sto_name": "STO Pattimura",
        "tipe": "STO",
        "rtu_kode": "",
        "is_offline": false,
        "is_online": false
      },
      {
        "id": "402",
        "id_pel_pln": "411022005025",
        "nama_pel_pln": "STO TERSILI",
        "tarif_pel_pln": "",
        "daya_pel_pln": "0",
        "lokasi_pel_pln": "TERSILI",
        "alamat_pel_pln": "",
        "gedung": "",
        "divre_kode": "TLK-r7000000",
        "divre_name": "DIVISI REGIONAL 7 KAWASAN TIMUR INDONESIA",
        "witel_kode": "DTT-lb200000",
        "witel_name": "TELKOM MALUKU (AMBON)",
        "sto_kode": "",
        "sto_name": "TLS Tersili",
        "tipe": "STO",
        "rtu_kode": "",
        "is_offline": false,
        "is_online": false
      },
      {
        "id": "405",
        "id_pel_pln": "411015034708",
        "nama_pel_pln": "PT. TELKOM",
        "tarif_pel_pln": "B2",
        "daya_pel_pln": "131000",
        "lokasi_pel_pln": "Maluku",
        "alamat_pel_pln": "JL.JB SITANALA , RAYON NUSANIWE",
        "gedung": "WITEL",
        "divre_kode": "TLK-r7000000",
        "divre_name": "DIVISI REGIONAL 7 KAWASAN TIMUR INDONESIA",
        "witel_kode": "DTT-lb200000",
        "witel_name": "TELKOM MALUKU (AMBON)",
        "sto_kode": "",
        "sto_name": "Ktr Witel Maluku",
        "tipe": "OFFICE",
        "rtu_kode": "",
        "is_offline": false,
        "is_online": false
      },
      {
        "id": "415",
        "id_pel_pln": "411090010713",
        "nama_pel_pln": "KANCATEL MASOHI",
        "tarif_pel_pln": "B2",
        "daya_pel_pln": "66000",
        "lokasi_pel_pln": "MASOHI - MALUKU",
        "alamat_pel_pln": "JLN. GESER NO.02, DESA NAMALEO, KECAMATAN KOTA MASOHI, KABUPATEN MALUKU TENGAH, MALUKU",
        "gedung": "EKS CATEL MASOHI",
        "divre_kode": "TLK-r7000000",
        "divre_name": "DIVISI REGIONAL 7 KAWASAN TIMUR INDONESIA",
        "witel_kode": "DTT-lb200000",
        "witel_name": "TELKOM MALUKU (AMBON)",
        "sto_kode": "MSH",
        "sto_name": "STO MASOHI",
        "tipe": "MIX",
        "rtu_kode": null,
        "is_offline": false,
        "is_online": false
      },
      {
        "id": "387",
        "id_pel_pln": "423110077017",
        "nama_pel_pln": "STASIUN BUMI BESAR",
        "tarif_pel_pln": "B3",
        "daya_pel_pln": "555000",
        "lokasi_pel_pln": "SORONG",
        "alamat_pel_pln": "JL.KOMPLEKS SKSD 77, 01 SORONG",
        "gedung": "SBB",
        "divre_kode": "TLK-r7000000",
        "divre_name": "DIVISI REGIONAL 7 KAWASAN TIMUR INDONESIA",
        "witel_kode": "DTT-ma200000",
        "witel_name": "TELKOM PAPUA BARAT (SORONG)",
        "sto_kode": "",
        "sto_name": "SBB Sorong",
        "tipe": "STO",
        "rtu_kode": "",
        "is_offline": false,
        "is_online": false
      },
      {
        "id": "391",
        "id_pel_pln": "423110198144",
        "nama_pel_pln": "KANTOR STO",
        "tarif_pel_pln": "B3",
        "daya_pel_pln": "240000",
        "lokasi_pel_pln": "SORONG",
        "alamat_pel_pln": "JL.A YANI SORONG",
        "gedung": "STO",
        "divre_kode": "TLK-r7000000",
        "divre_name": "DIVISI REGIONAL 7 KAWASAN TIMUR INDONESIA",
        "witel_kode": "DTT-ma200000",
        "witel_name": "TELKOM PAPUA BARAT (SORONG)",
        "sto_kode": "",
        "sto_name": "STO Sorong",
        "tipe": "STO",
        "rtu_kode": "",
        "is_offline": false,
        "is_online": false
      },
      {
        "id": "401",
        "id_pel_pln": "423510018736",
        "nama_pel_pln": "KANTOR SKSD FAK-FAK",
        "tarif_pel_pln": "B2",
        "daya_pel_pln": "105000",
        "lokasi_pel_pln": "SORONG",
        "alamat_pel_pln": "JLN BRAWIJAYA FAKFAK FF-1873 FAK-FAK",
        "gedung": "KANTOR",
        "divre_kode": "TLK-r7000000",
        "divre_name": "DIVISI REGIONAL 7 KAWASAN TIMUR INDONESIA",
        "witel_kode": "DTT-ma200000",
        "witel_name": "TELKOM PAPUA BARAT (SORONG)",
        "sto_kode": "",
        "sto_name": "STO Fakfak",
        "tipe": "MIX",
        "rtu_kode": "",
        "is_offline": false,
        "is_online": false
      },
      {
        "id": "389",
        "id_pel_pln": "421000082564",
        "nama_pel_pln": "KTR WIL XII TELKOM",
        "tarif_pel_pln": "B2",
        "daya_pel_pln": "197000",
        "lokasi_pel_pln": "Papua",
        "alamat_pel_pln": "JL. KAYU BATU BASE G JP- 8256",
        "gedung": "WITEL",
        "divre_kode": "TLK-r7000000",
        "divre_name": "DIVISI REGIONAL 7 KAWASAN TIMUR INDONESIA",
        "witel_kode": "DTT-mb200000",
        "witel_name": "TELKOM PAPUA (JAYA PURA)",
        "sto_kode": "",
        "sto_name": "NGN Base-G",
        "tipe": "MIX",
        "rtu_kode": "",
        "is_offline": false,
        "is_online": false
      },
      {
        "id": "397",
        "id_pel_pln": "421700032306",
        "nama_pel_pln": "PT TELKOM TIMIKA",
        "tarif_pel_pln": "B2",
        "daya_pel_pln": "164000",
        "lokasi_pel_pln": "Marisa",
        "alamat_pel_pln": "JL. TIMIKA INDAH , RAYON TIMIKA",
        "gedung": "PLASA",
        "divre_kode": "TLK-r7000000",
        "divre_name": "DIVISI REGIONAL 7 KAWASAN TIMUR INDONESIA",
        "witel_kode": "DTT-mb200000",
        "witel_name": "TELKOM PAPUA (JAYA PURA)",
        "sto_kode": "",
        "sto_name": "STO Timika",
        "tipe": "MIX",
        "rtu_kode": "",
        "is_offline": false,
        "is_online": false
      },
      {
        "id": "399",
        "id_pel_pln": "4214013002954",
        "nama_pel_pln": "PT TELKOM SARMI",
        "tarif_pel_pln": "B2",
        "daya_pel_pln": "82500",
        "lokasi_pel_pln": "SARMI",
        "alamat_pel_pln": "JL SARMI SARMI KOTA",
        "gedung": "",
        "divre_kode": "TLK-r7000000",
        "divre_name": "DIVISI REGIONAL 7 KAWASAN TIMUR INDONESIA",
        "witel_kode": "DTT-mb200000",
        "witel_name": "TELKOM PAPUA (JAYA PURA)",
        "sto_kode": "",
        "sto_name": "STO Sarmi",
        "tipe": "MIX",
        "rtu_kode": "",
        "is_offline": false,
        "is_online": false
      },
      {
        "id": "396",
        "id_pel_pln": "316000000201",
        "nama_pel_pln": "S T O - GORONTALO",
        "tarif_pel_pln": "B3",
        "daya_pel_pln": "240000",
        "lokasi_pel_pln": "Barru",
        "alamat_pel_pln": "JL.JAKSA A SUPRAPTO GAA 7803,TELAGA",
        "gedung": "STO + PLASA",
        "divre_kode": "TLK-r7000000",
        "divre_name": "DIVISI REGIONAL 7 KAWASAN TIMUR INDONESIA",
        "witel_kode": "DTT-mg200000",
        "witel_name": "TELKOM GORONTALO",
        "sto_kode": "",
        "sto_name": "STO Gorontalo",
        "tipe": "MIX",
        "rtu_kode": "",
        "is_offline": false,
        "is_online": false
      },
      {
        "id": "403",
        "id_pel_pln": "316210034403",
        "nama_pel_pln": "KTR PEL TELKOM",
        "tarif_pel_pln": "B2",
        "daya_pel_pln": "41500",
        "lokasi_pel_pln": "MAKASSAR",
        "alamat_pel_pln": "JL.KEL ISIMU UTARA GU003272. LIMBOTO",
        "gedung": "STO",
        "divre_kode": "TLK-r7000000",
        "divre_name": "DIVISI REGIONAL 7 KAWASAN TIMUR INDONESIA",
        "witel_kode": "DTT-mg200000",
        "witel_name": "TELKOM GORONTALO",
        "sto_kode": "",
        "sto_name": "STO Isimu",
        "tipe": "STO",
        "rtu_kode": "",
        "is_offline": false,
        "is_online": false
      },
      {
        "id": "404",
        "id_pel_pln": "316300005108",
        "nama_pel_pln": "PT TELKOM",
        "tarif_pel_pln": "B2",
        "daya_pel_pln": "53000",
        "lokasi_pel_pln": "Takalar",
        "alamat_pel_pln": "JL.DS MARISA GK001701.",
        "gedung": "PLASA",
        "divre_kode": "TLK-r7000000",
        "divre_name": "DIVISI REGIONAL 7 KAWASAN TIMUR INDONESIA",
        "witel_kode": "DTT-mg200000",
        "witel_name": "TELKOM GORONTALO",
        "sto_kode": "",
        "sto_name": "STO Marisa",
        "tipe": "STO",
        "rtu_kode": "",
        "is_offline": false,
        "is_online": false
      }
    ],
    "timestamp": "2023-05-23 13:36:06",
    "success": true
};