export default {
    "ike_data": [
        {
            "location": {
                "id": "212",
                "id_pel_pln": "161100041451\r\n",
                "nama_pel_pln": "KAKANDAT RATPON",
                "tarif_pel_pln": "B2",
                "daya_pel_pln": "82500",
                "lokasi_pel_pln": "Sumatera",
                "alamat_pel_pln": "JL PALAPA",
                "gedung": "PLASA",
                "divre_kode": "TLK-r1000000",
                "divre_name": "DIVISI REGIONAL 1 SUMATRA",
                "witel_kode": "DTB-bi200000",
                "witel_name": "TELKOM BANGKA BELITUNG (PANGKAL PINANG)",
                "sto_kode": "",
                "sto_name": "SLTA \/ SUNGAI LIAT",
                "tipe": "MIX",
                "rtu_kode": "",
                "tipe_perhitungan": "ike"
            },
            "ike": []
        },
        {
            "location": {
                "id": "211",
                "id_pel_pln": "163000085493\r\n",
                "nama_pel_pln": "KAKANCATEL TG.PANDAN",
                "tarif_pel_pln": "B2",
                "daya_pel_pln": "105000",
                "lokasi_pel_pln": "Sumatera",
                "alamat_pel_pln": "JL DOK",
                "gedung": "PLASA",
                "divre_kode": "TLK-r1000000",
                "divre_name": "DIVISI REGIONAL 1 SUMATRA",
                "witel_kode": "DTB-bi200000",
                "witel_name": "TELKOM BANGKA BELITUNG (PANGKAL PINANG)",
                "sto_kode": "",
                "sto_name": "TJNA \/ TANJUNG PANDAN",
                "tipe": "MIX",
                "rtu_kode": "",
                "tipe_perhitungan": "ike"
            },
            "ike": []
        },
        {
            "location": {
                "id": "215",
                "id_pel_pln": "146400011564",
                "nama_pel_pln": "SBK K DIESE",
                "tarif_pel_pln": "B2",
                "daya_pel_pln": "53000",
                "lokasi_pel_pln": "Bengkulu",
                "alamat_pel_pln": "JL A YANI",
                "gedung": "PLASA",
                "divre_kode": "TLK-r1000000",
                "divre_name": "DIVISI REGIONAL 1 SUMATRA",
                "witel_kode": "DTB-bh200000",
                "witel_name": "TELKOM BENGKULU (BENGKULU)",
                "sto_kode": "",
                "sto_name": "MNAA \/ MANNA",
                "tipe": "MIX",
                "rtu_kode": "",
                "tipe_perhitungan": "ike"
            },
            "ike": []
        },
        {
            "location": {
                "id": "217",
                "id_pel_pln": "143000610207",
                "nama_pel_pln": "PT. TELKOM",
                "tarif_pel_pln": "B2",
                "daya_pel_pln": "82500",
                "lokasi_pel_pln": "Jambi",
                "alamat_pel_pln": "JALAN SUMANTRI, TELANAI PURA",
                "gedung": "KANTOR",
                "divre_kode": "TLK-r1000000",
                "divre_name": "DIVISI REGIONAL 1 SUMATRA",
                "witel_kode": "DTB-bg200000",
                "witel_name": "TELKOM JAMBI",
                "sto_kode": "",
                "sto_name": "TLP \/ TELANAI PURA",
                "tipe": "STO",
                "rtu_kode": "",
                "tipe_perhitungan": "ike"
            },
            "ike": []
        },
        {
            "location": {
                "id": "225",
                "id_pel_pln": "181100054084",
                "nama_pel_pln": "PT (PERSERO)TELKOM",
                "tarif_pel_pln": "LB3",
                "daya_pel_pln": "690000",
                "lokasi_pel_pln": "Pekan Baru",
                "alamat_pel_pln": "JL. SUDIRMAN NO. 199 PBR",
                "gedung": "KANTOR",
                "divre_kode": "TLK-r1000000",
                "divre_name": "DIVISI REGIONAL 1 SUMATRA",
                "witel_kode": "DTB-be200000",
                "witel_name": "TELKOM RIAU DARATAN (PEKANBARU)",
                "sto_kode": "",
                "sto_name": "PBRC \/ PEKANBARU CENTRUM",
                "tipe": "MIX",
                "rtu_kode": "",
                "tipe_perhitungan": "ike"
            },
            "ike": []
        },
        {
            "location": {
                "id": "273",
                "id_pel_pln": "546200242164",
                "nama_pel_pln": "PT TELKOM",
                "tarif_pel_pln": "B3",
                "daya_pel_pln": "555000",
                "lokasi_pel_pln": "Jakarta",
                "alamat_pel_pln": "JL. STO LEGOK TGR",
                "gedung": "OPMC",
                "divre_kode": "TLK-r2000000",
                "divre_name": "DIVISI REGIONAL 2 JABOTABES",
                "witel_kode": "DTB-cb200000",
                "witel_name": "TELKOM BANTEN TIMUR (TANGERANG)",
                "sto_kode": "",
                "sto_name": "STO LEGOK",
                "tipe": "MIX",
                "rtu_kode": "",
                "tipe_perhitungan": "ike"
            },
            "ike": []
        },
        {
            "location": {
                "id": "274",
                "id_pel_pln": "546100080103",
                "nama_pel_pln": "S T O TANGERANG",
                "tarif_pel_pln": "B3",
                "daya_pel_pln": "865000",
                "lokasi_pel_pln": "Jakarta",
                "alamat_pel_pln": "JL. PASAR BARU TANGGERANG",
                "gedung": "OPMC",
                "divre_kode": "TLK-r2000000",
                "divre_name": "DIVISI REGIONAL 2 JABOTABES",
                "witel_kode": "DTB-cb200000",
                "witel_name": "TELKOM BANTEN TIMUR (TANGERANG)",
                "sto_kode": "",
                "sto_name": "STO TANGERANG",
                "tipe": "MIX",
                "rtu_kode": "",
                "tipe_perhitungan": "ike"
            },
            "ike": []
        },
        {
            "location": {
                "id": "247",
                "id_pel_pln": "538212439352",
                "nama_pel_pln": "GEDUNG OPMC",
                "tarif_pel_pln": "B3",
                "daya_pel_pln": "865000",
                "lokasi_pel_pln": "BOGOR",
                "alamat_pel_pln": "JL. PAJAJARAN",
                "gedung": "OPMC",
                "divre_kode": "TLK-r2000000",
                "divre_name": "DIVISI REGIONAL 2 JABOTABES",
                "witel_kode": "DTB-cj200000",
                "witel_name": "TELKOM JABAR BARAT (BOGOR)",
                "sto_kode": "",
                "sto_name": "GEDUNG OPMC BOGOR",
                "tipe": "OFFICE",
                "rtu_kode": "",
                "tipe_perhitungan": "ike"
            },
            "ike": []
        },
        {
            "location": {
                "id": "276",
                "id_pel_pln": "535593009582",
                "nama_pel_pln": "KANTOR PUSAT TELKOM",
                "tarif_pel_pln": "B3",
                "daya_pel_pln": "4330000",
                "lokasi_pel_pln": "Bandung",
                "alamat_pel_pln": "JL JAPATI",
                "gedung": "KANTOR",
                "divre_kode": "TLK-r3000000",
                "divre_name": "DIVISI REGIONAL 3 JABAR",
                "witel_kode": "DTT-AMC",
                "witel_name": "AMC",
                "sto_kode": "",
                "sto_name": "GRAHA MERAH PUTIH JAPATI",
                "tipe": "OFFICE",
                "rtu_kode": "",
                "tipe_perhitungan": "ike"
            },
            "ike": []
        },
        {
            "location": {
                "id": "278",
                "id_pel_pln": "535590769200",
                "nama_pel_pln": "LEMDIK",
                "tarif_pel_pln": "B2",
                "daya_pel_pln": "197000",
                "lokasi_pel_pln": "Bandung",
                "alamat_pel_pln": "JLGEGERKALONG",
                "gedung": "KANTOR + LC",
                "divre_kode": "TLK-r3000000",
                "divre_name": "DIVISI REGIONAL 3 JABAR",
                "witel_kode": "DTT-AMC",
                "witel_name": "AMC",
                "sto_kode": "",
                "sto_name": "LAB GERLONG",
                "tipe": "OFFICE",
                "rtu_kode": "",
                "tipe_perhitungan": "ike"
            },
            "ike": []
        },
        {
            "location": {
                "id": "286",
                "id_pel_pln": "535591237893",
                "nama_pel_pln": "DIVISI RISTI",
                "tarif_pel_pln": "B3",
                "daya_pel_pln": "1730000",
                "lokasi_pel_pln": "Bandung",
                "alamat_pel_pln": "JL. GEGERKALONG",
                "gedung": "KANTOR + LAB",
                "divre_kode": "TLK-r3000000",
                "divre_name": "DIVISI REGIONAL 3 JABAR",
                "witel_kode": "DTT-AMC",
                "witel_name": "AMC",
                "sto_kode": "",
                "sto_name": "LEA TELKOM",
                "tipe": "OFFICE",
                "rtu_kode": "",
                "tipe_perhitungan": "ike"
            },
            "ike": []
        },
        {
            "location": {
                "id": "294",
                "id_pel_pln": "536710001641",
                "nama_pel_pln": "KANT CAB TEL TELEG",
                "tarif_pel_pln": "B2",
                "daya_pel_pln": "197000",
                "lokasi_pel_pln": "CIANJUR",
                "alamat_pel_pln": "JL.RAYA CIPANAS",
                "gedung": "PLASA",
                "divre_kode": "TLK-r3000000",
                "divre_name": "DIVISI REGIONAL 3 JABAR",
                "witel_kode": "DTB-da200000",
                "witel_name": "WITEL SUKABUMI",
                "sto_kode": "",
                "sto_name": "PLASA SINDANGLAYA",
                "tipe": "MIX",
                "rtu_kode": "",
                "tipe_perhitungan": "ike"
            },
            "ike": []
        },
        {
            "location": {
                "id": "312",
                "id_pel_pln": "523010325873",
                "nama_pel_pln": "PT TELKOM INDONESIA",
                "tarif_pel_pln": "B3",
                "daya_pel_pln": "2180000",
                "lokasi_pel_pln": "Semarang",
                "alamat_pel_pln": "JL. PAHLAWAN 10, SEMARANG",
                "gedung": "PLASA + KANTOR",
                "divre_kode": "TLK-r4000000",
                "divre_name": "DIVISI REGIONAL 4 JATENG DIY",
                "witel_kode": "DTT-fc200000",
                "witel_name": "TELKOM JATENG UTARA (SEMARANG)",
                "sto_kode": "",
                "sto_name": "GMP PAHLAWAN - PHL",
                "tipe": "OFFICE",
                "rtu_kode": "",
                "tipe_perhitungan": "ike"
            },
            "ike": []
        },
        {
            "location": {
                "id": "362",
                "id_pel_pln": "513110649056",
                "nama_pel_pln": "PT TELKOM",
                "tarif_pel_pln": "B3",
                "daya_pel_pln": "1110000",
                "lokasi_pel_pln": "WITEL MALANG - WTL_MLG",
                "alamat_pel_pln": "AHMAD YANI NI. 11 BLIMBING",
                "gedung": "WITEL",
                "divre_kode": "TLK-r5000000",
                "divre_name": "DIVISI REGIONAL 5 JATIM",
                "witel_kode": "DTT-gc200000",
                "witel_name": "TELKOM JATIM SELATAN (MALANG)",
                "sto_kode": "",
                "sto_name": "WITEL MALANG - WTL_MLG",
                "tipe": "OFFICE",
                "rtu_kode": "",
                "tipe_perhitungan": "ike"
            },
            "ike": []
        },
        {
            "location": {
                "id": "360",
                "id_pel_pln": "516010574719",
                "nama_pel_pln": "PT TELKOM KANDATEL JR",
                "tarif_pel_pln": "B3",
                "daya_pel_pln": "690000",
                "lokasi_pel_pln": "WITEL JEMBER - WTL_JR",
                "alamat_pel_pln": "JL. GAJAHMADA NO 182",
                "gedung": "PLASA",
                "divre_kode": "TLK-r5000000",
                "divre_name": "DIVISI REGIONAL 5 JATIM",
                "witel_kode": "DTT-gg200000",
                "witel_name": "TELKOM JATIM TIMUR (JEMBER)",
                "sto_kode": "",
                "sto_name": "WITEL JEMBER - WTL_JR",
                "tipe": "OFFICE",
                "rtu_kode": "",
                "tipe_perhitungan": "ike"
            },
            "ike": []
        },
        {
            "location": {
                "id": "404",
                "id_pel_pln": "316300005108",
                "nama_pel_pln": "PT TELKOM",
                "tarif_pel_pln": "B2",
                "daya_pel_pln": "53000",
                "lokasi_pel_pln": "Takalar",
                "alamat_pel_pln": "JL.DS MARISA GK001701.",
                "gedung": "PLASA",
                "divre_kode": "TLK-r7000000",
                "divre_name": "DIVISI REGIONAL 7 KAWASAN TIMUR INDONESIA",
                "witel_kode": "DTT-mg200000",
                "witel_name": "TELKOM GORONTALO",
                "sto_kode": "",
                "sto_name": "STO Marisa",
                "tipe": "STO",
                "rtu_kode": "",
                "tipe_perhitungan": "ike"
            },
            "ike": []
        },
        {
            "location": {
                "id": "397",
                "id_pel_pln": "421700032306",
                "nama_pel_pln": "PT TELKOM TIMIKA",
                "tarif_pel_pln": "B2",
                "daya_pel_pln": "164000",
                "lokasi_pel_pln": "Marisa",
                "alamat_pel_pln": "JL. TIMIKA INDAH , RAYON TIMIKA",
                "gedung": "PLASA",
                "divre_kode": "TLK-r7000000",
                "divre_name": "DIVISI REGIONAL 7 KAWASAN TIMUR INDONESIA",
                "witel_kode": "DTT-mb200000",
                "witel_name": "TELKOM PAPUA (JAYA PURA)",
                "sto_kode": "",
                "sto_name": "STO Timika",
                "tipe": "MIX",
                "rtu_kode": "",
                "tipe_perhitungan": "ike"
            },
            "ike": []
        },
        {
            "location": {
                "id": "401",
                "id_pel_pln": "423510018736",
                "nama_pel_pln": "KANTOR SKSD FAK-FAK",
                "tarif_pel_pln": "B2",
                "daya_pel_pln": "105000",
                "lokasi_pel_pln": "SORONG",
                "alamat_pel_pln": "JLN BRAWIJAYA FAKFAK FF-1873 FAK-FAK",
                "gedung": "KANTOR",
                "divre_kode": "TLK-r7000000",
                "divre_name": "DIVISI REGIONAL 7 KAWASAN TIMUR INDONESIA",
                "witel_kode": "DTT-ma200000",
                "witel_name": "TELKOM PAPUA BARAT (SORONG)",
                "sto_kode": "",
                "sto_name": "STO Fakfak",
                "tipe": "MIX",
                "rtu_kode": "",
                "tipe_perhitungan": "ike"
            },
            "ike": []
        }
    ],
    "success": true
};