<?php

$this->result = [
    [ 'name' => 'NAD (ACEH)', 'code' => 'DTB-ba200000' ],
    [ 'name' => 'SUMUT TIMUR (PEMATANG SIANTAR)', 'code' => 'DTB-bb200000' ],
    [ 'name' => 'SUMUT BARAT (MEDAN)', 'code' => 'DTB-bc200000' ],
    [ 'name' => 'RIAU KEPULAUAN (BATAM)', 'code' => 'DTB-bd200000' ],
    [ 'name' => 'RIAU DARATAN (PEKANBARU)', 'code' => 'DTB-be200000' ],
    [ 'name' => 'SUMATERA BARAT (PADANG)', 'code' => 'DTB-bf200000' ],
    [ 'name' => 'JAMBI', 'code' => 'DTB-bg200000' ],
    [ 'name' => 'BENGKULU', 'code' => 'DTB-bh200000' ],
    [ 'name' => 'BANGKA BELITUNG (P.PINANG)', 'code' => 'DTB-bi200000' ],
    [ 'name' => 'SUMATERA SELATAN (PALEMBANG)', 'code' => 'DTB-bj200000' ],
    [ 'name' => 'LAMPUNG', 'code' => 'DTB-bk200000' ],
    
    [ 'name' => 'BANTEN BARAT (SERANG)', 'code' => 'DTB-ca200000' ],
    [ 'name' => 'BANTEN TIMUR (TANGERANG)', 'code' => 'DTB-cb200000' ],
    [ 'name' => 'JAKARTA BARAT', 'code' => 'DTB-cc200000' ],
    [ 'name' => 'JAKARTA PUSAT', 'code' => 'DTB-cd200000' ],
    [ 'name' => 'JAKARTA SELATAN', 'code' => 'DTB-ce200000' ],
    [ 'name' => 'JAKARTA UTARA', 'code' => 'DTB-cf200000' ],
    [ 'name' => 'JAKARTA TIMUR', 'code' => 'DTB-cg200000' ],
    [ 'name' => 'JABAR BARAT UTARA (BEKASI)', 'code' => 'DTB-ch200000' ],
    [ 'name' => 'JABAR BARAT (BOGOR)', 'code' => 'DTB-cj200000' ],

    [ 'name' => 'JABAR UTARA (KARAWANG)', 'code' => 'DTB-ci200000' ],
    [ 'name' => 'JABAR SELATAN (SUKABUMI)', 'code' => 'DTB-da200000' ],
    [ 'name' => 'BANDUNG', 'code' => 'DTB-db200000' ],
    [ 'name' => 'BANDUNG BARAT', 'code' => 'DTB-db2000x0' ],
    [ 'name' => 'JABAR TIMUR (CIREBON)', 'code' => 'DTB-dc200000' ],
    [ 'name' => 'JABAR TIMSEL (TASIKMALAYA)', 'code' => 'DTB-dd200000' ],

    [ 'name' => 'AMC', 'code' => 'DTT-AMC' ],

    [ 'name' => 'JATENG BARAT UTARA (PKLG)', 'code' => 'DTT-fa200000' ],
    [ 'name' => 'JATENG BARAT SELATAN (PWKT)', 'code' => 'DTT-fb200000' ],
    [ 'name' => 'JATENG UTARA (SEMARANG)', 'code' => 'DTT-fc200000' ],
    [ 'name' => 'JATENG TIMUR UTARA (KUDUS)', 'code' => 'DTT-fd200000' ],
    [ 'name' => 'JATENG SELATAN (MAGELANG)', 'code' => 'DTT-ff200000' ],
    [ 'name' => 'DI YOGYAKARTA', 'code' => 'DTT-fg200000' ],
    [ 'name' => 'JATENG TIMUR SELATAN (SOLO)', 'code' => 'DTT-fh200000' ],

    [ 'name' => 'JATIM TENGAH (KEDIRI)', 'code' => 'DTT-ga200000' ],
    [ 'name' => 'JATIM TENGAH (KEDIRI)', 'code' => 'DTT-ga200000' ],
    [ 'name' => 'JATIM BARAT (MADIUN)', 'code' => 'DTT-gb200000' ],
    [ 'name' => 'JATIM SELATAN (MALANG)', 'code' => 'DTT-gc200000' ],
    [ 'name' => 'JATIM SELATAN (MALANG)', 'code' => 'DTT-gc200000' ],
    [ 'name' => 'WITEL SURABAYA UTARA', 'code' => 'DTT-ge111111' ],
    [ 'name' => 'WITEL MADURA', 'code' => 'DTT-ge200000' ],
    [ 'name' => 'SURABAYA SELATAN', 'code' => 'DTT-ge222222' ],
    [ 'name' => 'JATIM TENGAH TIMUR (SIDOARJO)', 'code' => 'DTT-gf200000' ],
    // [ 'name' => 'JATIM TENGAH TIMUR  (SIDOARJO)', 'code' => 'DTT-gf200000' ],
    [ 'name' => 'JATIM TENGAH TIMUR (SIDOARJO)', 'code' => 'DTT-gf200000' ],
    [ 'name' => 'JEMBER', 'code' => 'DTT-gg200000' ],
    [ 'name' => 'JATIMSEL TIMUR (PASURUAN)', 'code' => 'DTT-gh200000' ],
    [ 'name' => 'BALI SELATAN (DENPASAR)', 'code' => 'DTT-ia200000' ],
    [ 'name' => 'BALI UTARA  (SINGARAJA)', 'code' => 'DTT-ib200000' ],
    [ 'name' => 'BALI UTARA (SINGARAJA)', 'code' => 'DTT-ib200000' ],
    [ 'name' => 'NTB (MATARAM)', 'code' => 'DTT-ja200000' ],
    [ 'name' => 'NTT (KUPANG)', 'code' => 'DTT-jb200000' ],
    
    [ 'name' => 'KALTIMTENG (SAMARINDA)', 'code' => 'DTT-ha200000' ],
    [ 'name' => 'KALTARA (TARAKAN)', 'code' => 'DTT-hb200000' ],
    [ 'name' => 'KALTIMSEL (BALIKPAPAN)', 'code' => 'DTT-hc200000' ],
    [ 'name' => 'KALBAR (PONTIANAK)', 'code' => 'DTT-hd200000' ],
    [ 'name' => 'KALTENG (PALANGKARAYA)', 'code' => 'DTT-he200000' ],
    [ 'name' => 'KALSEL (BANJARMASIN)', 'code' => 'DTT-hf200000' ],

    [ 'name' => 'MAKASSAR', 'code' => 'DTT-ka200000' ],
    [ 'name' => 'SULSELBAR', 'code' => 'DTT-kb200000' ],
    [ 'name' => 'SULTENG', 'code' => 'DTT-kc200000' ],
    [ 'name' => 'SULTRA', 'code' => 'DTT-kd200000' ],
    [ 'name' => 'SULUTMALUT', 'code' => 'DTT-kf200000' ],
    [ 'name' => 'MALUKU', 'code' => 'DTT-lb200000' ],
    [ 'name' => 'PAPUA BARAT', 'code' => 'DTT-ma200000' ],
    [ 'name' => 'PAPUA', 'code' => 'DTT-mb200000' ],
    [ 'name' => 'GORONTALO', 'code' => 'DTT-mg200000' ],
];